sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update
env:
  - RELEASE=../ga/21.0.0.12
  - RELEASE=../ga/22.0.0.3
  - RELEASE=../ga/22.0.0.6
  - RELEASE=../ga/latest

script:
- uname -a
- cat /etc/issue
- pwd
- cd test
- ./buildAll.sh $RELEASE
